### ISSUE TITLE
Solutions to MATLAB lab sessions

### ISSUE THREAD

**Issue by aakash298** [sdrangan/wirelesscomm#1]
Hello sir/madam , could you please post solutions to each lab session at end of each chapter. I want to cross check my answers.

**Comment by ghost** [comment]
already done.

**Comment by aakash298** [comment]
> already done.

**Comment by aakash298** [comment]
@hafatee, But I cant find solutions to lab experiments in any unit. If you happen to have them , could you post it here?

**Comment by aakash298** [comment]
@5hafatee, But I cant find solutions to lab experiments in any unit. If you happen to have them , could you post it here?

**Comment by sdrangan** [comment]
The solutions are *not* posted on the github site.  They are only available on NYU classes.

**Comment by ghost** [comment]
> 
> 
> @5hafatee, But I cant find solutions to lab experiments in any unit. If you happen to have them , could you post it here?

sorry i understood wrong.
